### ISSUE TITLE
[Task] Add Pull Request Template

### ISSUE THREAD

**Issue by tthvo** [k8s-crafts/ephemeral-containers-plugin#13]
Just like issue templates, we should also add a pull request template.

## Reference

- Example: https://github.com/devspace/awesome-github-templates
- Guide: https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository

**Comment by jfmartinz** [comment]
Please assign me this issue

**Comment by tthvo** [comment]
> Please assign me this issue

Assigned! Thanks @jfmartinz!

**Comment by jfmartinz** [comment]
I'll raise PR tomorrow.

**Comment by tthvo** [comment]
Done in #15
