### ISSUE TITLE
[Task] Unit test coverage report

### ISSUE THREAD

**Issue by tthvo** [k8s-crafts/ephemeral-containers-plugin#6]
Unit tests are available for the plugin but its coverage is not reported. This should be reported as part of push and pull-request status.

**Comment by abuzaforfagun** [comment]
I am interested in working on it.

**Comment by tthvo** [comment]
> I am interested in working on it.

Assigned, thanks @abuzaforfagun! 

Note that we do have coverage report generated (see `cover.out` when running `make test`). This issue focuses GitHub Action with the following requirement:

- [ ] A workflow that generated a markdown/html report and publish as a "sticky" comment (do not create new comments everytime) on pull request. 


Some inspirations:

- https://github.com/marketplace/actions/go-patch-coverage
- https://github.com/marocchino/sticky-pull-request-comment

**Comment by tthvo** [comment]
The step in question should be added to in the following job (after step `Run unit tests`): 

https://github.com/k8s-crafts/ephemeral-containers-plugin/blob/dd94cf46fb5375754b7d705dab2b723ae8000787/.github/workflows/test.yaml#L26
