### ISSUE TITLE
[Task] Increase golangci-lint timeout

### ISSUE THREAD

**Issue by tthvo** [k8s-crafts/ephemeral-containers-plugin#9]
Occasionally, there is a timeout error when running lints with golangci. We should increase the timeout. Perhaps `5m` is a good choice.

A failed run: https://github.com/k8s-crafts/ephemeral-containers-plugin/actions/runs/11411562471/job/31756031849?pr=8

## References

https://golangci-lint.run/usage/configuration/#run-configuration

**Comment by 5AIPAVAN** [comment]
can i take this :-) @tthvo

**Comment by 5AIPAVAN** [comment]
but it is already 5m right?

**Comment by tthvo** [comment]
> but it is already 5m right?

Hey @5AIPAVAN, I think the default is `1m` (see the timeout field, there is a comment above it) and we do not set it.

https://github.com/k8s-crafts/ephemeral-containers-plugin/blob/cf4ab5be570fb49cf8823e9aa75ec0191e53488a/.golangci.yaml#L1-L9

**Comment by tthvo** [comment]
Please let me know if you still want to work on it^^

**Comment by 5AIPAVAN** [comment]
chat gpt suggested me to modify .golangci.yaml with linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gci

run:
  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
  # Exit code when at least one issue was found.
  # Default: 1
  issues-exit-code: 2
  # Include test files or not.
  # Default: true
  tests: false


is that all

**Comment by abuzaforfagun** [comment]
I am interested to fix it.

**Comment by tthvo** [comment]
> I am interested in fixing it.

@abuzaforfagun Assigned. Thanks!
